apiVersion: apps/v1
kind: Deployment 
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
   matchLabels:
      app: example-voting-app
      name: db-app
  template:
    metadata:
      name: example-voting-app-pod
      labels:
        app: example-voting-app
        name: db-app
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
              - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: example-voting-app
    name: db-app