apiVersion: apps/v1
kind: Deployment 
metadata:
  name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-voting-app
      name: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: example-voting-app
        name: result-app 
    spec:
        containers:
            - name: result-app
              image: dockersamples/examplevotingapp_result
              ports:
                  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: example-voting-app
    name: result-app